spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/userdb
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  ##active决定使用哪个配置配置##
  profiles:
    active: dev